### ISSUE TITLE
Feature request: Update project function

### ISSUE THREAD

**Issue by ghost** [DiffyWebsite/diffy-php#4]
Aside from getting a projects details:

https://github.com/DiffyWebsite/diffy-php/blob/53121cd498907f3e960bd5c55995cc6083518b09/src/Project.php#L61-L70

I'm in need of a function to update a projects details.

**Comment by gregurco** [comment]
@verbruggenalex you can find it here: https://github.com/DiffyWebsite/diffy-php/blob/master/src/Project.php#L132
